# Numpy
* numpy array (배열)는 list와 유사하나 기능이 조금 다르다.
* numpy 배열과 list는 쉽게 변환 가능
* 리스트는 문자, 숫자, 리스트 등 다양한 요소를 넣을 수 있으나, numpy array는 한가지 데이터 타입만 저장 가능
* numpy array는 list와 달리 배열이 바로 연산 가능

* Numpy의 경우, 주로 np라는 명칭으로 임포트하는 것이 관례

In [1]:
data1 = [1.0,2,3,4,5]
import numpy as np
arr1 = np.array(data1)
print(arr1)
print(arr1.shape)
print(arr1.dtype)

[1. 2. 3. 4. 5.]
(5,)
float64


In [2]:
#2d array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
int64


* Numpy 생성

In [3]:
print(np.zeros(10))
print(np.zeros((3,5)))

print(np.ones(10))
print(np.ones((3,5)))

print(np.random.randn(10))
print(np.random.randn(3,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[-0.51422406 -1.0783624   0.07368445 -1.28025062 -0.69788314  0.67466691
 -0.01728615  0.90792338  0.18688339 -0.85564358]
[[-0.60361577  1.38689598  0.28547917 -0.45550057 -0.02313972]
 [ 0.23789213 -0.53316844 -1.07660691  1.24820523  0.33049822]
 [-0.53841474  0.32871479  0.32180069 -0.41542439  1.00685707]]


In [1]:
#list 연산
num = [1,3,4,8,-1]
num_100=[]
for i in num:
  num_100.append(i+100)
print(num_100) 
print(type(num_100))

[101, 103, 104, 108, 99]
<class 'list'>


In [5]:
# numpy array 연산
num = [1,3,4,8,-1]
num_arr = np.array(num) # 리스트를 numpy array로 변경
num_100 = num_arr + 100
print(num_100)
print(type(num_100))

[101 103 104 108  99]
<class 'numpy.ndarray'>


* 크기가 같은 Array 간의 연산
* 같은 위치에 있는 요소 간 연산

In [6]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[3,4,5],[6,7,8],[9,10,11]])
print(arr1)
print(arr2)
print(arr2-arr1)
print(arr2*arr1)
print(arr2/arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  8 15]
 [24 35 48]
 [63 80 99]]
[[3.         2.         1.66666667]
 [1.5        1.4        1.33333333]
 [1.28571429 1.25       1.22222222]]


* 크기가 다른 Array 간의 연산
* 브로드캐스트 기능을 통해 연산 가능

In [7]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([10,11,12])

print(arr3 + arr4)
print(arr3 *2)

[[11 13 15]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]]


* 행렬 곱은 np.dot
* 전치 행렬은 transpose

In [8]:
print(arr1)
print(arr2)
print(np.dot(arr1, arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 42  48  54]
 [ 96 111 126]
 [150 174 198]]


In [9]:
print(arr1)
print(arr1.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


* Numpy array의 기초통계량 계산

In [10]:
arr1 = np.random.randn(5,3)
print(arr1)

print(arr1.sum())
print(arr1.min())
print(arr1.max())
print(arr1.mean()) # 평균
print(arr1.std()) # 표준편차
print(arr1.var()) # 분산

[[-0.87771991 -1.61728124  0.5786692 ]
 [ 1.75253166 -0.47231066  0.67368614]
 [ 0.85246198  0.87999939 -1.62191474]
 [-0.89374903 -0.89679506  0.8848055 ]
 [ 1.60545324  0.61212739  0.58286995]]
2.042833800841759
-1.6219147415115922
1.7525316563897235
0.13618892005611727
1.0645956911789825
1.1333639856768551


* 특정 범위 가져오기
* 리스트와 동일

In [11]:
arr1 = np.random.randint(10, size = 10)
print(arr1)
print(arr1[-1])
print(arr1[1:3])

[3 0 1 6 4 5 1 9 1 4]
4
[0 1]


# Pandas
* pandas에서는 기본적으로 정의되는 자료구조인 Series와 Data Frame을 사용
* Series는 python의 list와 유사한 성격을 가진 형태로 일련의 데이터를 저장할 수 있는 공간
* DataFrame 은 여러개의 Series를 저장할 수 있는 공간
* 데이터를 엑셀처럼 다루도록 지원하고, R의 데이터프레임에서 착안한 라이브러리

* Pandas의 경우, 주로 pd라는 명칭으로 임포트하는 것이 관례

In [12]:
import pandas as pd

* Series는 1차원 배열 형태로 리스트, 딕셔너리 형태로 생성 가능

In [13]:
series1 = pd.Series([4, 7, -5, 3])
print(series1)

0    4
1    7
2   -5
3    3
dtype: int64


In [14]:
series2 = pd.Series({'3월':100, '4월':80, '5월':90, '6월':80, '7월':150})
print(series2)

3월    100
4월     80
5월     90
6월     80
7월    150
dtype: int64


* DataFrame
* 2차 배열 형태를 데이터프레임이라고 하며,인덱스(행의 이름)와 column 값을 가진다.

In [15]:
data = {'name': ['Lee', 'Kim', 'Hwang', 'Kim', 'Park'],
        'year': [2014, 2018, 2020, 2021, 2019],
        'points': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data)
print(df)

    name  year  points
0    Lee  2014     1.5
1    Kim  2018     1.7
2  Hwang  2020     3.6
3    Kim  2021     2.4
4   Park  2019     2.9


* Dataframe 인덱싱

* 열 선택

In [16]:
print(df['year'])
print(df.year)

0    2014
1    2018
2    2020
3    2021
4    2019
Name: year, dtype: int64
0    2014
1    2018
2    2020
3    2021
4    2019
Name: year, dtype: int64


In [17]:
print(df[['year','points']])

   year  points
0  2014     1.5
1  2018     1.7
2  2020     3.6
3  2021     2.4
4  2019     2.9


* 열 수정

In [18]:
df['points']=[0.5, 0.7, 0.6, 0.4, 0.9]
print(df)

    name  year  points
0    Lee  2014     0.5
1    Kim  2018     0.7
2  Hwang  2020     0.6
3    Kim  2021     0.4
4   Park  2019     0.9


* 열 제거

In [19]:
del df['points']
print(df)

    name  year
0    Lee  2014
1    Kim  2018
2  Hwang  2020
3    Kim  2021
4   Park  2019


* sklearn에서 제공하는 데이터셋 불러오기
* Boston housing data

In [20]:
from sklearn import datasets
boston=datasets.load_boston()
boston=pd.DataFrame(boston.data, columns=boston.feature_names)
boston

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [21]:
boston.head(10)
#boston.tail(10)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
5  0.02985   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.12   5.21
6  0.08829  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  395.60  12.43
7  0.14455  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  396.90  19.15
8  0.21124  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  386.63  29.93
9  0.17004  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  386.71  17.10

[10 rows x 13 columns]

In [22]:
boston.describe()

CRIM          ZN       INDUS  ...     PTRATIO           B       LSTAT
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...   18.455534  356.674032   12.653063
std      8.601545   23.322453    6.860353  ...    2.164946   91.294864    7.141062
min      0.006320    0.000000    0.460000  ...   12.600000    0.320000    1.730000
25%      0.082045    0.000000    5.190000  ...   17.400000  375.377500    6.950000
50%      0.256510    0.000000    9.690000  ...   19.050000  391.440000   11.360000
75%      3.677083   12.500000   18.100000  ...   20.200000  396.225000   16.955000
max     88.976200  100.000000   27.740000  ...   22.000000  396.900000   37.970000

[8 rows x 13 columns]

* Dataframe 슬라이싱
* 데이터 프레임을 슬라이싱 하는 방법은 무수히 많다.
* 대표적인 것이 loc 와 iloc 를 사용하는 방법

* loc[행의 조건, 열의 조건]을 통해서 필요한 부분만 선택가능함

In [23]:
boston.loc[:10]

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0   0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1   0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2   0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3   0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4   0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
5   0.02985   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.12   5.21
6   0.08829  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  395.60  12.43
7   0.14455  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  396.90  19.15
8   0.21124  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  386.63  29.93
9   0.17004  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  386.71  17.10
10  0.22489  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  392.52  20.45

[11 rows x 13 columns]

In [24]:
boston.loc[[1,2,3,9,10], ['AGE', 'TAX']]

AGE    TAX
1   78.9  242.0
2   61.1  242.0
3   45.8  222.0
9   85.9  311.0
10  94.3  311.0

* 특정 조건 탐색 가능

In [25]:
boston.loc[boston['ZN']>10, 'NOX']=0.25
boston.head(10)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.250  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
5  0.02985   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.12   5.21
6  0.08829  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  395.60  12.43
7  0.14455  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  396.90  19.15
8  0.21124  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  386.63  29.93
9  0.17004  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  386.71  17.10

[10 rows x 13 columns]

In [26]:
c = boston.loc[boston.AGE>70, :]
c

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
7    0.14455  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  396.90  19.15
8    0.21124  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  386.63  29.93
9    0.17004  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  386.71  17.10
10   0.22489  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  392.52  20.45
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
500  0.22438   0.0   9.69   0.0  0.585  ...  6.0  391.0     19.2  396.90  14.33
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[287 rows x 13 columns]

* iloc는 인덱스의 값과 관계없이 데이터 사이즈 숫자를 활용해 데이터를 불러온다.

In [27]:
c.loc[:10]

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
1   0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
7   0.14455  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  396.90  19.15
8   0.21124  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  386.63  29.93
9   0.17004  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  386.71  17.10
10  0.22489  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  392.52  20.45

[5 rows x 13 columns]

In [28]:
c.iloc[:10]

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
1   0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
7   0.14455  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  396.90  19.15
8   0.21124  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  386.63  29.93
9   0.17004  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  386.71  17.10
10  0.22489  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  392.52  20.45
11  0.11747  12.5   7.87   0.0  0.250  ...  5.0  311.0     15.2  396.90  13.27
14  0.63796   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  380.02  10.26
17  0.78420   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  386.75  14.67
20  1.25179   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  376.57  21.02
21  0.85204   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  392.53  13.83

[10 rows x 13 columns]

In [29]:
c.iloc[:5,2:7]

INDUS  CHAS    NOX     RM    AGE
1    7.07   0.0  0.469  6.421   78.9
7    7.87   0.0  0.250  6.172   96.1
8    7.87   0.0  0.250  5.631  100.0
9    7.87   0.0  0.250  6.004   85.9
10   7.87   0.0  0.250  6.377   94.3

* 결측값 처리

In [30]:
df = pd.DataFrame(np.random.randn(6,4))
df.columns = ['A', 'B', 'C', 'D']
df.index = pd.date_range('20210301', periods=6)

# np.nan은 NaN값을 의미한다.
df['F'] = [1.0, np.nan, 3.5, 6.1, np.nan, 7.0]
df

A         B         C         D    F
2021-03-01  0.145646  0.073572  1.296432 -0.714812  1.0
2021-03-02 -2.251444 -1.401461 -0.613817 -1.407364  NaN
2021-03-03  0.601095 -0.026947  0.178559 -0.771118  3.5
2021-03-04 -0.517090 -0.497579  0.200657 -1.541854  6.1
2021-03-05  0.087907  1.268616  0.743204  0.833113  NaN
2021-03-06  0.456795 -0.142060 -0.892366 -1.132033  7.0

In [31]:
# 행의 값중 하나라도 nan인 경우 그 행을 없앤다.
df.dropna(how='any')

A         B         C         D    F
2021-03-01  0.145646  0.073572  1.296432 -0.714812  1.0
2021-03-03  0.601095 -0.026947  0.178559 -0.771118  3.5
2021-03-04 -0.517090 -0.497579  0.200657 -1.541854  6.1
2021-03-06  0.456795 -0.142060 -0.892366 -1.132033  7.0

In [32]:
# 행의 값의 모든 값이 nan인 경우 그 행을 없앤다.
df.dropna(how='all')

A         B         C         D    F
2021-03-01  0.145646  0.073572  1.296432 -0.714812  1.0
2021-03-02 -2.251444 -1.401461 -0.613817 -1.407364  NaN
2021-03-03  0.601095 -0.026947  0.178559 -0.771118  3.5
2021-03-04 -0.517090 -0.497579  0.200657 -1.541854  6.1
2021-03-05  0.087907  1.268616  0.743204  0.833113  NaN
2021-03-06  0.456795 -0.142060 -0.892366 -1.132033  7.0

In [33]:
# nan값인지 확인하기
df.isnull()

A      B      C      D      F
2021-03-01  False  False  False  False  False
2021-03-02  False  False  False  False   True
2021-03-03  False  False  False  False  False
2021-03-04  False  False  False  False  False
2021-03-05  False  False  False  False   True
2021-03-06  False  False  False  False  False

In [34]:
# F열에서 nan값을 포함하는 행만 추출하기
df.loc[df['F'].isnull()]

A         B         C         D   F
2021-03-02 -2.251444 -1.401461 -0.613817 -1.407364 NaN
2021-03-05  0.087907  1.268616  0.743204  0.833113 NaN

In [35]:
# nan값에 값 넣기
df.fillna(value=1000)

A         B         C         D       F
2021-03-01  0.145646  0.073572  1.296432 -0.714812     1.0
2021-03-02 -2.251444 -1.401461 -0.613817 -1.407364  1000.0
2021-03-03  0.601095 -0.026947  0.178559 -0.771118     3.5
2021-03-04 -0.517090 -0.497579  0.200657 -1.541854     6.1
2021-03-05  0.087907  1.268616  0.743204  0.833113  1000.0
2021-03-06  0.456795 -0.142060 -0.892366 -1.132033     7.0

* 데이터프레임 삭제 추가

In [36]:
students=[
     {'id':1, '언어':80, '수학':60, '외국어':100},
     {'id':2, '언어':100, '수학':90, '외국어':90},
     {'id':3, '언어':40, '수학':90, '외국어':60},
     {'id':4, '언어':50, '수학':30, '외국어':50}, 
     {'id':5, '언어':80, '수학':80, '외국어':80}, 
     {'id':6, '언어':70, '수학':60, '외국어':10} 
]
df=pd.DataFrame(students)
df

id   언어  수학  외국어
0   1   80  60  100
1   2  100  90   90
2   3   40  90   60
3   4   50  30   50
4   5   80  80   80
5   6   70  60   10

In [37]:
df.drop([1,3])

id  언어  수학  외국어
0   1  80  60  100
2   3  40  90   60
4   5  80  80   80
5   6  70  60   10

In [38]:
df.drop(['언어'],axis=1)

id  수학  외국어
0   1  60  100
1   2  90   90
2   3  90   60
3   4  30   50
4   5  80   80
5   6  60   10

* 데이터 프레임 추가

In [39]:
new={'id':7, '언어':90, '수학':90, '외국어':90}
df2=df.append(new, ignore_index = True)
df2

id   언어  수학  외국어
0   1   80  60  100
1   2  100  90   90
2   3   40  90   60
3   4   50  30   50
4   5   80  80   80
5   6   70  60   10
6   7   90  90   90

In [40]:
df3=df.append(df2)
df3

id   언어  수학  외국어
0   1   80  60  100
1   2  100  90   90
2   3   40  90   60
3   4   50  30   50
4   5   80  80   80
5   6   70  60   10
0   1   80  60  100
1   2  100  90   90
2   3   40  90   60
3   4   50  30   50
4   5   80  80   80
5   6   70  60   10
6   7   90  90   90

In [41]:
df3=df.append(df2, ignore_index = True)
df3

id   언어  수학  외국어
0    1   80  60  100
1    2  100  90   90
2    3   40  90   60
3    4   50  30   50
4    5   80  80   80
5    6   70  60   10
6    1   80  60  100
7    2  100  90   90
8    3   40  90   60
9    4   50  30   50
10   5   80  80   80
11   6   70  60   10
12   7   90  90   90